### ISSUE TITLE
Iaew manolão

### ISSUE THREAD

**Issue by napalmdev** [igorvidottof/geolocation_test#1]
falaaaaa Jovi, fui te mandar msg no Facebook mas sua conta sumiu de lá, ai não tenho seu número pra mandar zap tbm duashduhsudsad, essa foi a única maneira de me comunicar, malz ai man udashduashdudhsaudhsaudsadh

que da hora que vc ta voltando pro mundo de Dev mano \o/ \o/ \o/, precisar de qualquer coisa só falar manolo, amigo é pra essas paradas pÔ, chama eu la no zap 14-99621-3275, abração Shelderaaaa

**Comment by igorvidottof** [comment]
uauishiuahuidhuaishduiahsuidhuiashd I vanished from the face of the Earth man! kkkkkkkkkkkkkkkkkkkkkkkk valeeeeeu mano, vou te chamar lá parçaaa!
